# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
STEAM_WEB_API_KEY: 'XXXXX'
GMAIL_PASSWORD: 'XXXXX'
MANDRILL_USERNAME: 'XXXXX'
MANDRILL_API_KEY: 'XXXXX'
STRIPE_API_KEY: 'XXXXX'
STRIPE_PUBLIC_KEY: 'XXXXX'
CHALLONGE_USER: 'XXXXX'
CHALLONGE_KEY: 'XXXXX'
